required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    ]

[prune]
  go-tests = true

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  #revision = "0734939e05aeb64ab198e3feeee8b4e90ee5cbb2"
  branch = "master"

[[constraint]]
  branch = "cluster-api-to-latest"
  name = "github.com/openshift/cluster-api-actuator-pkg"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/libvirt/libvirt-go"
  version = "4.6.0"

[[constraint]]
  name = "github.com/libvirt/libvirt-go-xml"
  version = "4.6.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "ae27198cdd90bf12cd134ad79d1366a6cf49f632"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "=1.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

# STANZAS BELOW ARE GENERATED AND MAY BE WRITTEN - DO NOT MODIFY BELOW THIS LINE.

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="v0.1.1"

[[constraint]]
  name="sigs.k8s.io/controller-tools"
  version="v0.1.1"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"
